#!/bin/bash

## Description: Install the project
## Usage: install
## Example: "ddev install"
## ProjectTypes: drupal8,drupal9

# Abort if anything fails
set -e

echo -e "\n\033[1;36m Installing Drupal Dependencies.\033[0m"
ddev composer install --apcu-autoloader

#echo -e "\n\033[1;36m Installing and building Wingsuit theme.\033[0m"
#ddev drupal:theme

ddev drush -y si --existing-config

ddev drush -y deploy

echo -e "\n\033[1;36m Enabling development modules and configuration.\033[0m"
ddev drush -y en twig_vardumper devel_kint_extras
ddev drush -y config:set devel.settings devel_dumper kint_extended

echo -e "\n\033[1;36m Install complete. Login with the following url:\033[0m"
ddev drush uli
