_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  coi: 0
  component_blocks: 0
  components: 0
  config: 0
  config_override_core_fields: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_kint_extras: 0
  diff: 0
  drimage: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_lb: 0
  gin_login: 0
  gin_toolbar: 0
  image: 0
  inline_form_errors: 0
  layout_builder: 0
  layout_builder_browser: 0
  layout_builder_component_attributes: 0
  layout_builder_modal: 0
  layout_builder_operation_link: 0
  layout_builder_restrictions: 0
  layout_builder_restrictions_by_region: 0
  layout_builder_st: 0
  layout_discovery: 0
  link: 0
  link_attributes: 0
  linkit: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_remote: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  section_library: 0
  section_library_reusable: 0
  symfony_mailer: 0
  symfony_mailer_bc: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  twig_vardumper: 0
  ui_patterns: 0
  ui_patterns_extends: 0
  ui_patterns_field_formatters: 0
  ui_patterns_layout_builder: 0
  ui_patterns_layouts: 0
  ui_patterns_library: 0
  ui_patterns_views: 0
  ui_patterns_views_style: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  minimal: 1000
theme:
  claro: 0
  stable: 0
  gin: 0
  tailwindcss: 0
profile: minimal
